AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Deploy an BattleSnake endpoint running a ready to use AI model
Globals:
  Function:
    Runtime: python3.6
    MemorySize: 1024
Resources:
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Events:
        ApiEvent:
          Properties:
            Method: get
            Path: /start
            RestApiId:
              Ref: ApiGatewayApi
          Type: Api
      Handler: index.handler
      CodeUri: s3://yvr-immersion-days/cloudformation/lambda.zip
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: demo
Outputs:
  ProdDataEndpoint:
    Description: "Snake endpoint"
    Value: !Sub "https://${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/demo/"


            