AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Deploy an BattleSnake endpoint running a ready to use AI model
Globals:
  Function:
    Runtime: python3.7
    MemorySize: 1024
Mappings: 
  RegionMap:
    ap-northeast-2:
      "MxnetLayerArn": "arn:aws:lambda:ap-northeast-2:752200179490:layer:AWSLambda-Python37-MXNet:1"
      "SciPyLayerArn": "arn:aws:lambda:ap-northeast-2:296580773974:layer:AWSLambda-Python37-SciPy1x:2"
    ap-southeast-2:
      "MxnetLayerArn": "arn:aws:lambda:ap-southeast-2:752200179490:layer:AWSLambda-Python37-MXNet:1"
      "SciPyLayerArn": "arn:aws:lambda:ap-southeast-2:817496625479:layer:AWSLambda-Python37-SciPy1x:2"
    sa-east-1:
      "MxnetLayerArn": "arn:aws:lambda:sa-east-1:752200179490:layer:AWSLambda-Python37-MXNet:1"
      "SciPyLayerArn": "arn:aws:lambda:sa-east-1:640010853179:layer:AWSLambda-Python37-SciPy1x:2"
    eu-west-1:
      "MxnetLayerArn": "arn:aws:lambda:eu-west-1:752200179490:layer:AWSLambda-Python37-MXNet:1"
      "SciPyLayerArn": "arn:aws:lambda:eu-west-1:399891621064:layer:AWSLambda-Python37-SciPy1x:2"
    eu-west-3:
      "MxnetLayerArn": "arn:aws:lambda:eu-west-3:752200179490:layer:AWSLambda-Python37-MXNet:1"
      "SciPyLayerArn": "arn:aws:lambda:eu-west-3:959311844005:layer:AWSLambda-Python37-SciPy1x:2"
    us-east-1:
      "MxnetLayerArn": "arn:aws:lambda:us-east-1:752200179490:layer:AWSLambda-Python37-MXNet:1"
      "SciPyLayerArn": "arn:aws:lambda:us-east-1:668099181075:layer:AWSLambda-Python37-SciPy1x:2"
    us-west-2:
      "MxnetLayerArn": "arn:aws:lambda:us-west-2:752200179490:layer:AWSLambda-Python37-MXNet:1"
      "SciPyLayerArn": "arn:aws:lambda:us-west-2:420165488524:layer:AWSLambda-Python37-SciPy1x:2"
    ca-central-1:
      "MxnetLayerArn": "arn:aws:lambda:ca-central-1:752200179490:layer:AWSLambda-Python37-MXNet:1"
      "SciPyLayerArn": "arn:aws:lambda:ca-central-1:778625758767:layer:AWSLambda-Python37-SciPy1x:2"
Parameters:
  S3Bucket:
    Description: The bucket where the Lamba package is
    Type: String
  S3Key:
    Description: Key of the lambda package
    Type: String
    Default: lambda/model-lambda-package.zip
Resources:
  PingFunction:
    Type: AWS::Serverless::Function
    Properties:
      Events:
        ApiEvent:
          Properties:
            Method: post
            Path: /ping
            RestApiId:
              Ref: ApiGatewayApi
          Type: Api
      Handler: lambda.ping
      Layers:
        - !FindInMap [RegionMap, !Ref "AWS::Region", MxnetLayerArn]
        - !FindInMap [RegionMap, !Ref "AWS::Region", SciPyLayerArn]
      CodeUri:
        Bucket: !Ref S3Bucket
        Key: !Ref S3Key
  EndFunction:
    Type: AWS::Serverless::Function
    Properties:
      Events:
        ApiEvent:
          Properties:
            Method: post
            Path: /end
            RestApiId:
              Ref: ApiGatewayApi
          Type: Api
      Handler: lambda.end
      Layers:
        - !FindInMap [RegionMap, !Ref "AWS::Region", MxnetLayerArn]
        - !FindInMap [RegionMap, !Ref "AWS::Region", SciPyLayerArn]
      CodeUri:
        Bucket: !Ref S3Bucket
        Key: !Ref S3Key
  MoveFunction:
    Type: AWS::Serverless::Function
    Properties:
      Events:
        ApiEvent:
          Properties:
            Method: post
            Path: /move
            RestApiId:
              Ref: ApiGatewayApi
          Type: Api
      Handler: lambda.move
      Layers:
        - !FindInMap [RegionMap, !Ref "AWS::Region", MxnetLayerArn]
        - !FindInMap [RegionMap, !Ref "AWS::Region", SciPyLayerArn]
      CodeUri:
        Bucket: !Ref S3Bucket
        Key: !Ref S3Key
  StartFunction:
    Type: AWS::Serverless::Function
    Properties:
      Events:
        ApiEvent:
          Properties:
            Method: any
            Path: /start
            RestApiId:
              Ref: ApiGatewayApi
          Type: Api
      Handler: lambda.start
      Layers:
        - !FindInMap [RegionMap, !Ref "AWS::Region", MxnetLayerArn]
        - !FindInMap [RegionMap, !Ref "AWS::Region", SciPyLayerArn]
      CodeUri:
        Bucket: !Ref S3Bucket
        Key: !Ref S3Key
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: demo
Outputs:
  SnakeUrl:
    Description: "Snake URL"
    Value: !Sub "https://${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/demo/"
  StartMethod:
    Description: "Start method URL"
    Value: !Sub "https://${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/demo/start"


            
