AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Deploy an BattleSnake endpoint running a ready to use AI model
Globals:
  Function:
    Runtime: python2.7
    MemorySize: 1024
Parameters:
  S3Bucket:
    Description: The bucket where the Lamba package is
    Type: String
  S3Key:
    Description: Key of the lambda package
    Type: String
Resources:
  PingFunction:
    Type: AWS::Serverless::Function
    Properties:
      Events:
        ApiEvent:
          Properties:
            Method: post
            Path: /ping
            RestApiId:
              Ref: ApiGatewayApi
          Type: Api
      Handler: lambda.ping
      Layers:
        - !Sub "arn:aws:lambda:${AWS::Region}:778625758767:layer:AWSLambda-Python27-SciPy1x:2"
      CodeUri:
        Bucket: !Ref S3Bucket
        Key: !Ref S3Key
  EndFunction:
    Type: AWS::Serverless::Function
    Properties:
      Events:
        ApiEvent:
          Properties:
            Method: post
            Path: /end
            RestApiId:
              Ref: ApiGatewayApi
          Type: Api
      Handler: lambda.end
      Layers:
        - !Sub "arn:aws:lambda:${AWS::Region}:778625758767:layer:AWSLambda-Python27-SciPy1x:2"
      CodeUri:
        Bucket: !Ref S3Bucket
        Key: !Ref S3Key
  MoveFunction:
    Type: AWS::Serverless::Function
    Properties:
      Events:
        ApiEvent:
          Properties:
            Method: post
            Path: /move
            RestApiId:
              Ref: ApiGatewayApi
          Type: Api
      Handler: lambda.move
      Layers:
        - !Sub "arn:aws:lambda:${AWS::Region}:778625758767:layer:AWSLambda-Python27-SciPy1x:2"
      CodeUri:
        Bucket: !Ref S3Bucket
        Key: !Ref S3Key
  StartFunction:
    Type: AWS::Serverless::Function
    Properties:
      Events:
        ApiEvent:
          Properties:
            Method: any
            Path: /start
            RestApiId:
              Ref: ApiGatewayApi
          Type: Api
      Handler: lambda.start
      Layers:
        - !Sub "arn:aws:lambda:${AWS::Region}:778625758767:layer:AWSLambda-Python27-SciPy1x:2"
      CodeUri:
        Bucket: !Ref S3Bucket
        Key: !Ref S3Key
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: demo
Outputs:
  SnakeUrl:
    Description: "Snake URL"
    Value: !Sub "https://${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/demo/"
  StartMethod:
    Description: "Start method URL"
    Value: !Sub "https://${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/demo/start"


            
