AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Deploy an BattleSnake endpoint running a ready to use AI model
Globals:
  Function:
    Runtime: python2.7
    MemorySize: 1024
Mappings: 
  RegionMap: 
    us-west-2: 
      "SciPyLayerArn": "arn:aws:lambda:us-west-2:420165488524:layer:AWSLambda-Python27-SciPy1x:2"
    ca-central-1: 
      "SciPyLayerArn": "arn:aws:lambda:ca-central-1:778625758767:layer:AWSLambda-Python27-SciPy1x:2"
Resources:
  PingFunction:
    Type: AWS::Serverless::Function
    Properties:
      Events:
        ApiEvent:
          Properties:
            Method: post
            Path: /ping
            RestApiId:
              Ref: ApiGatewayApi
          Type: Api
      Handler: lambda.ping
      Layers:
        - !FindInMap [RegionMap, !Ref "AWS::Region", SciPyLayerArn]
      CodeUri:
        Bucket: !Sub battlesnake-aws-${AWS::Region}
        Key: lambda/model-lambda-package.zip
  EndFunction:
    Type: AWS::Serverless::Function
    Properties:
      Events:
        ApiEvent:
          Properties:
            Method: post
            Path: /end
            RestApiId:
              Ref: ApiGatewayApi
          Type: Api
      Handler: lambda.end
      Layers:
        - !FindInMap [RegionMap, !Ref "AWS::Region", SciPyLayerArn]
      CodeUri:
        Bucket: !Sub battlesnake-aws-${AWS::Region}
        Key: lambda/model-lambda-package.zip
  MoveFunction:
    Type: AWS::Serverless::Function
    Properties:
      Events:
        ApiEvent:
          Properties:
            Method: post
            Path: /move
            RestApiId:
              Ref: ApiGatewayApi
          Type: Api
      Handler: lambda.move
      Layers:
        - !FindInMap [RegionMap, !Ref "AWS::Region", SciPyLayerArn]
      CodeUri:
        Bucket: !Sub battlesnake-aws-${AWS::Region}
        Key: lambda/model-lambda-package.zip
  StartFunction:
    Type: AWS::Serverless::Function
    Properties:
      Events:
        ApiEvent:
          Properties:
            Method: any
            Path: /start
            RestApiId:
              Ref: ApiGatewayApi
          Type: Api
      Handler: lambda.start
      Layers:
        - !FindInMap [RegionMap, !Ref "AWS::Region", SciPyLayerArn]
      CodeUri:
        Bucket: !Sub battlesnake-aws-${AWS::Region}
        Key: lambda/model-lambda-package.zip
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: demo
Outputs:
  SnakeUrl:
    Description: "Snake URL"
    Value: !Sub "https://${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/demo/"
  StartMethod:
    Description: "Start method URL"
    Value: !Sub "https://${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/demo/start"


            
